// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {

}
declare module '*.vue' {
    import { defineComponent } from 'vue'
    const component: ReturnType<typeof defineComponent>
    export default component
}
export {}
